### ISSUE TITLE
add wp shortcode functionality?

### ISSUE THREAD

**Issue by matthewselby** [terminalpixel/Developer-Share-Buttons#2]
Awesome plugin! I don't think I see this as a feature set and if not then it would be awesome to have the ability to drop in share buttons with shortcode.

**Comment by krishaamer** [comment]
+1

**Comment by grantcodes** [comment]
I already have a shortcode in there, just undocumented at the moment `[dev_share_buttons]` to create sharing buttons for the current page

**Comment by matthewselby** [comment]
@grantcodes Sweet! Thank you for your reply. I will check out using the shortcode above.
